# Generated by Django 5.0.7 on 2024-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_company_address_alter_company_company_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
